services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "YourStrong!Passw0rd"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

  api:
    build: .
    env_file: .env
    depends_on:
      - sqlserver
    ports:
      - "8000:8000"
    environment:
      SQL_SERVER_HOST: sqlserver

volumes:
  sql_data: